### ISSUE TITLE
Not able to find the find the RallyObject file(class) in the bundle

### ISSUE THREAD

**Issue by arunbcodes** [markwilliams970/RallyRestToolkitForVBA#1]
Not sure if I am missing something or if this is an issue.. I am not able to find the RallyObject file (class) in the zip file and hence it gives a compilation error.

**Comment by markwilliams970** [comment]
Sorry for the trouble and the slow reply. It looks like I need to re-export the source code as there may be a class missing. Also, I'll work up a working example macro and post a sample spreadsheet with instructions showing the steps to get it to run.

**Comment by markwilliams970** [comment]
Added missing class file. Updated code with additional samples. Uploaded starter Excel Worksheet with VBA project structure and code samples, and fleshed out the README.

**Comment by SmartUser10** [comment]
Hi Mark, I tried the excel file you have attached and it errors out saying the Parameter is Incorrect. On Debug it stops at this line.

```
Set myProject = myRallyRestApi.findProject(myWorkspace, RallyProject)
```

Any help...

**Comment by markwilliams970** [comment]
Sorry for the slow reply and for the hassle - this should be fixed via the most recent commit.
