### ISSUE TITLE
oHttp.Send("") - Timeout Issue

### ISSUE THREAD

**Issue by bhavinkotak** [markwilliams970/RallyRestToolkitForVBA#4]
Hi, I am facing issue of "The operation timed out" during oHttp.Send("") step present in httpGET function. Can u please help getting it resolved?
When I manually try to enter the Url, Login details on browser - its working fine; so doesn't look like to be proxy/firewall issue.

**Comment by markwilliams970** [comment]
I tested request on httpGET and it is working in my testing. Do you know if you are using a Proxy server? At this point the toolkit has not been tested in a proxied environment, and it's not clear if VBA supports an HTTP request using a proxy.

**Comment by kdunc2015** [comment]
I can’t thank you enough for all your help today!!!
