### ISSUE TITLE
Adapt for Feature data pull

### ISSUE THREAD

**Issue by kdunc2015** [markwilliams970/RallyRestToolkitForVBA#5]
Hello, 

I have really benefited from your toolkit. Thank you so much for building it. I am very new to Rally, so please excuse me if this is a dumb question. It appears that your toolkit is built to retrieve story level data. Although, I have combed through the code and I don't see an implicit reference to story data in particular. I would like to adapt the toolkit to retrieve story and/or feature level data. Can you refer me to which class module outlines what is pulled? Thank you again!

**Comment by markwilliams970** [comment]
Hi kdunc2015. The toolkit as written should have the ability to pull portfolio items. All you have to do is specify a different ArtifactName in your RallyRequest. Featires have a WSAPI endpoint of "portfolioitem/feature", so if you are using the default Rally portfolio hierarchy, that is the ArtifactName you would need to use. Here's a link to a Gist:

https://gist.github.com/markwilliams970/94b97088874e47d061e8

That shows an example of doing this. Of course, if you've renamed or have custom names for your PortolioItems, you would need to use the corresponding naming convention for your artifact type.

**Comment by kdunc2015** [comment]
Awesome! You saved me again ☺ Thank you for getting back to me so quickly too!!
